# 2nd Oct. Numpy Crash Course

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [9]:
np.array([2,4,56,422,32,1]) # ID array

array([  2,   4,  56, 422,  32,   1])

In [11]:
a = np.array([2,4,56,422,32,1]) # Vector
print(a)

[  2   4  56 422  32   1]


In [13]:
type(a)

numpy.ndarray

In [22]:
# 2D Array (Matrix)
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [30]:
# 3D --- # Tensor
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

# dtype

In [33]:
np.array([11,23,44] , dtype =float)

array([11., 23., 44.])

In [35]:
np.array([11,23,44] , dtype = int)

array([11, 23, 44])

In [41]:
np.array([56,75,45] , dtype =bool) # Here True becoz , python treats Non - zero

array([ True,  True,  True])

In [43]:
np.array([46,34,45] , dtype =complex)

array([46.+0.j, 34.+0.j, 45.+0.j])

In [125]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [127]:
type(my_list)

list

In [129]:
arr = np.array(my_list)

In [131]:
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

In [17]:
type(my_list)

list

In [ ]:
np.

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(3.0)

array([0., 1., 2.])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.arange(20,10)

array([], dtype=int32)

In [33]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [39]:
np.arange(10,10)

array([], dtype=int32)

In [25]:
b = np.arange(30,20)
b

array([], dtype=int32)

In [29]:
b = np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [41]:
np.arange()

TypeError: arange() requires stop to be specified.

In [45]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [47]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [31]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [35]:
b1 = np.zeros(2) # Parameter tunning 
b1

array([0., 0.])

In [37]:
np.zeros(5,dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [53]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [39]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [51]:
np.zeros((5,10)) # bytefaul 1arg -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [57]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [15]:
zero = np.zeros([2,2])
print('##########')
print(type(zero))

##########
<class 'numpy.ndarray'>


In [19]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
n

(6, 7)

In [69]:
n1

(6, 8)

In [77]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [73]:
np.ones((5,4), dtype=int) # by default 5 - rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((6,7),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

# Please add new notebook & compare with np & *

In [18]:
from numpy import * # internally it called all 217 functionalist
arange(3)

array([0, 1, 2])

In [20]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
>>> from numpy import *
>>> arange(3)

array([0, 1, 2])

In [24]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [26]:
>>> from numpy import *
>>> zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.random.rand(4)

array([0.77203365, 0.45919594, 0.482756  , 0.90027161])

In [23]:
np.random.rand(2,4)

array([[0.4636792 , 0.33918857, 0.23073659, 0.95190556],
       [0.9975044 , 0.68947745, 0.23080321, 0.15004933]])

In [25]:
np.random.randint(2,4)

3

In [44]:
np.random.randint(2,20) # 2nd argument is exclusive

18

In [52]:
np.random.randint(0,2)

0

In [66]:
np.random.randint(1,10,4)

array([9, 5, 7, 8])

In [68]:
np.random.randint(1,3,5)

array([1, 2, 2, 1, 1])

In [61]:
np.random.randint(2,20,2)

array([11, 12])

In [8]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [70]:
np.random.randint(1)

0

In [76]:
np.random.randint(5,9) #Get the value <=1 & >=5

7

In [78]:
np.random.randint(10,21,3)

array([14, 19, 14])

In [80]:
np.random.randint(1,12,10)

array([ 6,  7,  4,  3, 11,  1,  7,  2,  2,  5])

# 3rd Oct -->

In [35]:
np.random.randint(20,30,10)

array([25, 20, 25, 28, 24, 21, 25, 29, 20, 27])

In [74]:
b = np.random.randint(10,40,(10,10))
b

array([[16, 30, 26, 10, 24, 36, 20, 14, 11, 21],
       [38, 34, 31, 20, 36, 37, 31, 32, 19, 29],
       [30, 31, 18, 35, 27, 25, 16, 17, 27, 13],
       [17, 30, 35, 23, 37, 14, 35, 25, 29, 27],
       [17, 16, 29, 16, 35, 17, 13, 39, 26, 30],
       [11, 30, 36, 19, 14, 34, 28, 12, 26, 28],
       [36, 32, 24, 26, 34, 21, 23, 22, 38, 19],
       [23, 29, 15, 36, 24, 30, 31, 26, 28, 35],
       [29, 31, 29, 30, 11, 32, 17, 25, 28, 20],
       [29, 39, 22, 22, 10, 25, 38, 23, 30, 20]])

In [86]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 17, 19, 11],
       [15, 17, 11, 16],
       [19, 10, 11, 15],
       [17, 13, 17, 19],
       [18, 19, 11, 12]])

In [72]:
np.random.randint(10,20,(5,10))

array([[10, 12, 11, 18, 12, 16, 18, 19, 14, 11],
       [10, 14, 16, 15, 18, 19, 15, 17, 16, 10],
       [12, 11, 14, 18, 17, 15, 13, 16, 18, 14],
       [11, 13, 17, 12, 14, 13, 18, 10, 11, 19],
       [11, 10, 15, 12, 19, 19, 13, 16, 13, 16]])

In [88]:
b[:]

array([[15, 17, 19, 11],
       [15, 17, 11, 16],
       [19, 10, 11, 15],
       [17, 13, 17, 19],
       [18, 19, 11, 12]])

In [90]:
b[0:2]

array([[15, 17, 19, 11],
       [15, 17, 11, 16]])

In [92]:
b

array([[15, 17, 19, 11],
       [15, 17, 11, 16],
       [19, 10, 11, 15],
       [17, 13, 17, 19],
       [18, 19, 11, 12]])

In [94]:
b[0:-1]

array([[15, 17, 19, 11],
       [15, 17, 11, 16],
       [19, 10, 11, 15],
       [17, 13, 17, 19]])

In [105]:
b

array([[15, 17, 19, 11],
       [15, 17, 11, 16],
       [19, 10, 11, 15],
       [17, 13, 17, 19],
       [18, 19, 11, 12]])

In [109]:
b[0,2]

19

In [111]:
np.random.randint(10,20,(4,4))

array([[12, 13, 17, 19],
       [17, 11, 19, 16],
       [14, 18, 15, 11],
       [15, 11, 12, 10]])

# Operations

In [119]:
a = np.random.randint(10,20,5)
a

array([16, 10, 15, 18, 10])

In [133]:
arr

array([0, 1, 2, 3, 4, 5])

In [186]:
arr2 = np.random.randint(0,100,(10,10))

In [188]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [175]:
arr

array([0, 1, 2, 3, 4, 5])

In [177]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [179]:
arr[:4]

array([0, 1, 2, 3])

In [183]:
arr2[:]

array([[53,  2, 55, 59, 35, 45, 67, 35, 92, 77],
       [65,  9, 56,  0, 62, 19, 73, 22, 34, 17],
       [97, 88, 82, 49, 55, 66, 88,  7, 58, 73],
       [18,  0, 42, 60, 43, 59, 71, 20, 96, 52],
       [98, 88, 26, 10, 17,  4,  0, 11, 20, 18],
       [86, 60, 26, 48, 89, 20, 99, 41, 35, 55],
       [52, 25, 64, 55, 28, 18, 85, 61, 80, 50],
       [50, 50, 44, 51, 67, 94, 45, 49, 42, 16],
       [52, 57, 31, 41, 55, 20, 13, 18, 53, 42],
       [73, 49, 79, 17, 96, 96, 27, 81,  9, 99]])

In [192]:
arr2[0:5]

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74]])

In [201]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [203]:
arr2[1,5]

7

In [205]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [207]:
arr2[-5,5]

41

In [209]:
arr2[-5,-5]

41

In [211]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [213]:
arr2[-5,-5]

41

In [215]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [217]:
arr2[-1,-2]

8

In [219]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [221]:
arr2[::-1]

array([[ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [99, 63,  9, 33, 78, 37, 26, 75, 10, 90]])

In [223]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [225]:
arr2[::-2]

array([[ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89]])

In [227]:
arr2

array([[99, 63,  9, 33, 78, 37, 26, 75, 10, 90],
       [27, 81, 29, 38, 57,  7,  8, 92, 84, 89],
       [39, 82, 31,  8, 98, 16, 77, 25, 78, 71],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [22, 86, 99,  1, 84, 95, 61, 42, 56, 74],
       [77, 58, 62, 87, 94, 41, 68, 40, 34, 12],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [27, 25, 76, 98, 40, 12, 79, 99, 32, 28],
       [24, 66, 58, 91, 55, 74, 98, 58, 43,  8],
       [ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69]])

In [229]:
arr2[::-3]

array([[ 3, 34, 85, 71, 49, 57, 12, 92,  8, 69],
       [ 4, 80, 84, 46, 21, 82,  9, 69, 30, 41],
       [61, 66, 87, 91, 81, 56,  8, 53, 16, 16],
       [99, 63,  9, 33, 78, 37, 26, 75, 10, 90]])

In [231]:
arr

array([0, 1, 2, 3, 4, 5])

In [233]:
arr.max()

5

In [235]:
arr.min()

0

In [237]:
arr

array([0, 1, 2, 3, 4, 5])

In [239]:
arr.mean()

2.5

In [241]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [243]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [245]:
arr

array([0, 1, 2, 3, 4, 5])

In [247]:
arr

array([0, 1, 2, 3, 4, 5])

In [249]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [251]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [253]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [255]:
arr

array([0, 1, 2, 3, 4, 5])

In [257]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [259]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [261]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [263]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [265]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [267]:
arr

array([0, 1, 2, 3, 4, 5])

In [269]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [271]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [273]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [275]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [277]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [279]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [281]:
arr

array([0, 1, 2, 3, 4, 5])

In [283]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [292]:
mat = np.arange(0,100).reshape(10,10)

In [288]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
row = 4
col = 5

In [296]:
col

5

In [298]:
row

4

In [300]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [302]:
mat[row,col]

45

In [304]:
mat[4,5]

45

In [306]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [308]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
col = 6

In [312]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [314]:
# With Slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [316]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [318]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [320]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [322]:
row

4

In [324]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [326]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [328]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [330]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [332]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [336]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [338]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [340]:
row

4

In [342]:
col

6

In [344]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [346]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [352]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [350]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [354]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [356]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [358]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [360]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [362]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [364]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [366]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [368]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [372]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [374]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [376]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [378]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [380]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [382]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [384]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [386]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [390]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [392]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [394]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [396]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [398]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [400]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [402]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [404]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [406]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [408]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [410]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [412]:
mat[0,1]

1

In [414]:
mat[1,6]

16

In [420]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [416]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [422]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [424]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [426]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [428]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [430]:
mat[3,5]

35

In [432]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [434]:
mat[1:2,2:4]

array([[12, 13]])

In [436]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [438]:
mat[2:3,2:3]

array([[22]])

In [442]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [440]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [444]:
mat[2:3,4:5]

array([[24]])

# Masking

In [447]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [449]:
id(mat)

2437836978672

In [451]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [453]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [455]:
mat > 50 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [457]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [459]:
mat[mat==50]

array([50])

In [461]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [463]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [465]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [469]:
a3= mat[mat>=50]
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [471]:
a4 = mat[mat==50]
a4

array([50])

In [473]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [475]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [477]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])